import { useState, type FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { homeFor } from '../components/ProtectedRoute';
import { useAuth } from '../lib/auth';
import { usersApi } from '../lib/endpoints';
import { describeError } from '../lib/errors';

const MIN_LENGTH = 8;

/**
 * Forced password change for an account created by an invitation.
 *
 * Such an account's first password was generated by AdaptiveHire and sent in
 * plaintext to an inbox, where it stays readable indefinitely. Until it is
 * replaced, anyone who reads that email — or the forwarded copy, or the shared
 * screen it was opened on — can sit the assessment as this candidate. So the
 * change is a gate rather than a suggestion, enforced in `ProtectedRoute`.
 *
 * The current password is asked for rather than assumed: the change-password
 * endpoint verifies it, which is what keeps a hijacked session from quietly
 * locking the real candidate out of their own account.
 */
export function SetPassword() {
  const { user, updateUser } = useAuth();
  const navigate = useNavigate();

  const [current, setCurrent] = useState('');
  const [next, setNext] = useState('');
  const [confirm, setConfirm] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const tooShort = next.length > 0 && next.length < MIN_LENGTH;
  const mismatch = confirm.length > 0 && next !== confirm;
  const ready =
    current.length > 0 && next.length >= MIN_LENGTH && next === confirm;

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    if (!ready || !user) return;

    setBusy(true);
    setError(null);
    try {
      await usersApi.changePassword(current, next);
      // The server cleared the flag; mirror it locally so the gate opens
      // without a round trip through a full profile reload.
      updateUser({ mustChangePassword: false });
      void navigate(homeFor(user.role), { replace: true });
    } catch (err) {
      const status = (err as { response?: { status?: number } }).response
        ?.status;
      setError(
        status === 401
          ? 'Password did not match the given one. Please type the given password.'
          : describeError(err, 'Could not set your password.'),
      );
    } finally {
      setBusy(false);
    }
  };

  return (
    <div className="gate-screen">
      <div className="card gate-card">
        <div className="card-head">
          <h1>Choose your own password</h1>
        </div>

        <form className="card-pad stack" onSubmit={(e) => void submit(e)}>
          <p className="muted" style={{ marginTop: 0 }}>
            We emailed you a password so you could sign in. Replace it with one
            only you know — the emailed one stops working straight away.
          </p>

          {error && <div className="alert error">{error}</div>}

          <div className="field">
            <label htmlFor="current">Password from your invitation email</label>
            <input
              id="current"
              type="password"
              autoComplete="current-password"
              value={current}
              onChange={(e) => setCurrent(e.target.value)}
              required
            />
          </div>

          <div className="field">
            <label htmlFor="next">New password</label>
            <input
              id="next"
              type="password"
              autoComplete="new-password"
              value={next}
              onChange={(e) => setNext(e.target.value)}
              required
            />
            <p className={`field-note${tooShort ? ' error-note' : ''}`}>
              At least {MIN_LENGTH} characters.
            </p>
          </div>

          <div className="field">
            <label htmlFor="confirm">Confirm new password</label>
            <input
              id="confirm"
              type="password"
              autoComplete="new-password"
              value={confirm}
              onChange={(e) => setConfirm(e.target.value)}
              required
            />
            {mismatch && (
              <p className="field-note error-note">
                These two do not match yet.
              </p>
            )}
          </div>

          <button className="primary block" type="submit" disabled={!ready || busy}>
            {busy ? 'Saving…' : 'Save and continue'}
          </button>
        </form>
      </div>
    </div>
  );
}
