import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Invited candidates now receive working credentials by email instead of a link
 * to go and register themselves.
 *
 * That means the password a candidate first signs in with was generated by us
 * and sent in plaintext to an inbox, where it stays readable forever. So a
 * provisioned account is flagged here and must set its own password before it
 * can reach an assessment — after which the emailed one is worthless.
 *
 * Defaults to `false`, so nobody who already has an account is forced through
 * the change screen: their password was always their own, and only accounts
 * created by the invite flow set this to `true`.
 */
export class CredentialInvites1786570000000 implements MigrationInterface {
  name = 'CredentialInvites1786570000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "users"
        ADD COLUMN "mustChangePassword" boolean NOT NULL DEFAULT false
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
      ALTER TABLE "users" DROP COLUMN "mustChangePassword"
    `);
  }
}
