import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  OneToMany,
  PrimaryGeneratedColumn,
  UpdateDateColumn,
} from 'typeorm';
import { OrgRole, UserRole } from '../../common/enums';
import { Organisation } from '../../organisations/entities/organisation.entity';

export interface RecentRefreshToken {
  /** Argon2 hash — the plaintext token never touches the database. */
  hash: string;
  /** ISO timestamp of when this token was superseded. */
  at: string;
}
import { Invitation } from '../../invitations/entities/invitation.entity';
import { AssessmentSession } from '../../sessions/entities/assessment-session.entity';

@Entity('users')
export class User {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Index({ unique: true })
  @Column({ type: 'varchar', length: 255 })
  email!: string;

  @Column({ type: 'varchar', length: 255, select: false })
  passwordHash!: string;

  /**
   * Hash of the currently-valid refresh token, so logout and rotation can
   * invalidate it server-side. The token itself only ever lives in an
   * httpOnly cookie.
   */
  @Column({ type: 'varchar', length: 255, nullable: true, select: false })
  hashedRefreshToken!: string | null;

  /**
   * Hashes of recently-superseded refresh tokens, newest first, each accepted
   * for a short grace window.
   *
   * A single previous slot is not enough: rapid navigation can leave the
   * browser holding a token that was issued but never used, which then matches
   * neither the current token nor the one predecessor, and the session gets
   * revoked mid-session. Keeping the last few closes that gap while reuse of a
   * genuinely unknown token still revokes immediately.
   */
  @Column({ type: 'jsonb', nullable: true, select: false })
  recentRefreshTokens!: RecentRefreshToken[] | null;

  @Column({ type: 'varchar', length: 150 })
  fullName!: string;

  @Column({ type: 'enum', enum: UserRole })
  role!: UserRole;

  /**
   * The hiring company this account belongs to, and the scope of everything it
   * can see.
   *
   * Set for every `recruiter_admin` and null for every candidate — a candidate
   * belongs to no company, and sits assessments for whoever invites them. The
   * column is nullable because of that, not because a recruiter may go without
   * one: registration always creates the pair together.
   */
  @Column({ type: 'uuid', nullable: true })
  organisationId!: string | null;

  @ManyToOne(() => Organisation, (organisation) => organisation.members, {
    onDelete: 'CASCADE',
    nullable: true,
  })
  @JoinColumn({ name: 'organisationId' })
  organisation!: Organisation | null;

  /**
   * What this account may do inside its organisation.
   *
   * A second axis to `role`, not a replacement: `role` says which side of the
   * platform someone is on, this says what they may do once inside a
   * workspace. Null for every candidate, permanently, since they belong to no
   * organisation.
   *
   * Nullable rather than defaulted so a missing value is visible instead of
   * silently becoming a permission — `OrgRolesGuard` refuses a recruiter with
   * no `orgRole` rather than waving them through.
   */
  @Column({ type: 'enum', enum: OrgRole, nullable: true })
  orgRole!: OrgRole | null;

  @Column({ type: 'boolean', default: true })
  isActive!: boolean;

  /**
   * Set when the account was provisioned by an invitation, so its first password
   * was generated by us and emailed in plaintext. Such an account must choose
   * its own password before it can reach an assessment; a candidate who
   * registered themselves never had that problem and is never flagged.
   */
  @Column({ type: 'boolean', default: false })
  mustChangePassword!: boolean;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt!: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt!: Date;

  @OneToMany(() => Invitation, (invitation) => invitation.candidate)
  invitations!: Invitation[];

  @OneToMany(() => AssessmentSession, (session) => session.candidate)
  sessions!: AssessmentSession[];
}
